### ISSUE TITLE
Kalliope responds only to the first request

### ISSUE THREAD

**Issue by gahujipo** [andweber/loxberry-plugin-kalliope#2]
Kalliope responds only to the first request. After a reboot Kalliope is responding again. Sometimes the answer for multiple questions afterwards gets outputted in simultaneously. 

This happens on both the request via the API (mentioned [here](http://www.loxwiki.eu/display/LOXBERRY/Kalliope?focusedCommentId=18219302#comment-18219302)) and test commands on the webinterface of kalliope in loxyberry.

Are you able to reproduce the issue?

**Comment by andweber** [comment]
not sure without seeing a log, but I know that the loxberry currently has an issue with pulseaudio which leads to a not responding kalliope and simultaneous output after sometime or retriggering - this sounds bretty similiar. 

It can be fixed by switching to alsa, but mplayer - which is used by kalliope - seems to have a similar problem as pulseaudio - thus there is no simple fix. There is already an issue for kalliope https://github.com/kalliope-project/kalliope/issues/234

**Comment by lufiacs** [comment]
@andweber, do you think this issue could probably be resolved by using the new features in kalliope 0.4.4?

**Comment by gahujipo** [comment]
@andweber, do you think this issue could probably be resolved by using the new features in kalliope 0.4.4?

**Comment by andweber** [comment]
yes I think so, I will upgrade to 0.4.4 as soon as I find time to test and commit

**Comment by andweber** [comment]
should be fixed with recent master and dev (head - no release yet), please check and open a new issue if you still have problems
